$ErrorActionPreference = "Stop"
$root   = $PSScriptRoot
$mods   = Join-Path $root "modules"
$out    = Join-Path $root "w3dimporter.ms"
$banner = "-- AUTO-GENERATED by build-w3dimporter.ps1 — edit modules/, not this file --`r`n"

$files = Get-ChildItem $mods -Filter "*.ms" | Sort-Object Name
if ($files.Count -lt 10) { Write-Error "expected >=10 module files, found $($files.Count)"; exit 1 }

$ms = New-Object System.IO.MemoryStream
$enc = New-Object System.Text.UTF8Encoding($false)
$bannerBytes = $enc.GetBytes($banner)
$ms.Write($bannerBytes, 0, $bannerBytes.Length)
foreach ($f in $files) {
    $b = [System.IO.File]::ReadAllBytes($f.FullName)
    $ms.Write($b, 0, $b.Length)   # raw concat, no separator
}
[System.IO.File]::WriteAllBytes($out, $ms.ToArray())
Write-Host ("BUILD OK -> w3dimporter.ms ({0} bytes) from: {1}" -f $ms.Length, ($files.Name -join ', '))
