$ErrorActionPreference = "Stop"
$root   = Split-Path -Parent $PSScriptRoot
$legacy = Join-Path $root "legacy\w3dimporter-v21.4.ms"
$built  = Join-Path $root "w3dimporter.ms"
$mods   = Join-Path $root "modules"
$banner = "-- AUTO-GENERATED by build-w3dimporter.ps1 — edit modules/, not this file --`r`n"
$enc    = New-Object System.Text.UTF8Encoding($false)

function Sha($bytes) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    [BitConverter]::ToString($sha.ComputeHash($bytes)).Replace("-","")
}

# --- baseline body: legacy lines 1..6485 ---
$lb = [System.IO.File]::ReadAllBytes($legacy)
$nl = 0; $cut = -1
for ($i = 0; $i -lt $lb.Length - 1; $i++) {
    if ($lb[$i] -eq 13 -and $lb[$i+1] -eq 10) { $nl++; if ($nl -eq 6485) { $cut = $i + 2; break } }
}
$legacyBody = New-Object byte[] $cut; [System.Array]::Copy($lb, 0, $legacyBody, 0, $cut)

# --- rebuilt expectation: banner + concat(00..08) + concat(99) ---
$defFiles = Get-ChildItem $mods -Filter "0?-*.ms" | Sort-Object Name
$regFiles = Get-ChildItem $mods -Filter "99-*.ms" | Sort-Object Name
$bannerBytes = $enc.GetBytes($banner)
$concatDef = New-Object System.IO.MemoryStream
foreach ($f in $defFiles) { $b=[IO.File]::ReadAllBytes($f.FullName); $concatDef.Write($b,0,$b.Length) }
$defBytes = $concatDef.ToArray()
$concatReg = New-Object System.IO.MemoryStream
foreach ($f in $regFiles) { $b=[IO.File]::ReadAllBytes($f.FullName); $concatReg.Write($b,0,$b.Length) }
$regBytes = $concatReg.ToArray()

$expected = New-Object System.IO.MemoryStream
$expected.Write($bannerBytes,0,$bannerBytes.Length)
$expected.Write($defBytes,0,$defBytes.Length)
$expected.Write($regBytes,0,$regBytes.Length)
$expectedBytes = $expected.ToArray()
$builtBytes = [IO.File]::ReadAllBytes($built)

# (a) baseline body check: concat(00..08) must equal legacy body
Write-Host ("baseline: legacyBody={0}b sha={1}" -f $legacyBody.Length, (Sha $legacyBody))
Write-Host ("baseline: concatDef ={0}b sha={1}" -f $defBytes.Length,   (Sha $defBytes))
if ((Sha $legacyBody) -ne (Sha $defBytes)) { Write-Error "BASELINE BODY DRIFT"; exit 1 }

# (b) rebuilt determinism: built file == banner + def + reg
Write-Host ("rebuilt:  built   ={0}b sha={1}" -f $builtBytes.Length,    (Sha $builtBytes))
Write-Host ("rebuilt:  expected={0}b sha={1}" -f $expectedBytes.Length, (Sha $expectedBytes))
if ((Sha $builtBytes) -ne (Sha $expectedBytes)) { Write-Error "BUILD NONDETERMINISTIC / EXTRA BYTES"; exit 1 }

Write-Host "BUILD GUARD OK"
exit 0
