$ErrorActionPreference = "Stop"
$root   = Split-Path -Parent $PSScriptRoot
$built  = Join-Path $root "w3dimporter.ms"
$mods   = Join-Path $root "modules"
$banner = "-- AUTO-GENERATED by build-w3dimporter.ps1 — edit modules/, not this file --`r`n"
$enc    = New-Object System.Text.UTF8Encoding($false)

function Sha($bytes) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    [BitConverter]::ToString($sha.ComputeHash($bytes)).Replace("-","")
}

# --- rebuilt expectation: banner + concat(00..08) + concat(99) ---
$defFiles = Get-ChildItem $mods -Filter "0?-*.ms" | Sort-Object Name
$regFiles = Get-ChildItem $mods -Filter "99-*.ms" | Sort-Object Name
$bannerBytes = $enc.GetBytes($banner)
$concatDef = New-Object System.IO.MemoryStream
foreach ($f in $defFiles) { $b=[IO.File]::ReadAllBytes($f.FullName); $concatDef.Write($b,0,$b.Length) }
$defBytes = $concatDef.ToArray()
$concatReg = New-Object System.IO.MemoryStream
foreach ($f in $regFiles) { $b=[IO.File]::ReadAllBytes($f.FullName); $concatReg.Write($b,0,$b.Length) }
$regBytes = $concatReg.ToArray()

$expected = New-Object System.IO.MemoryStream
$expected.Write($bannerBytes,0,$bannerBytes.Length)
$expected.Write($defBytes,0,$defBytes.Length)
$expected.Write($regBytes,0,$regBytes.Length)
$expectedBytes = $expected.ToArray()
$builtBytes = [IO.File]::ReadAllBytes($built)

# rebuilt determinism: built file == banner + concat(modules)
# (proves w3dimporter.ms is mechanically generated from modules and never hand-edited)
Write-Host ("rebuilt:  built   ={0}b sha={1}" -f $builtBytes.Length,    (Sha $builtBytes))
Write-Host ("rebuilt:  expected={0}b sha={1}" -f $expectedBytes.Length, (Sha $expectedBytes))
if ((Sha $builtBytes) -ne (Sha $expectedBytes)) { Write-Error "BUILD NONDETERMINISTIC / EXTRA BYTES"; exit 1 }

Write-Host "BUILD GUARD OK"
exit 0
